package com.gillsoft.model;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceExternalSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceExternalSoap {


    /**
     * 
     * @return
     *     returns org.tempuri.ArrayOfCityS
     */
    @WebMethod(operationName = "GetCity", action = "http://tempuri.org/GetCity")
    @WebResult(name = "GetCityResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCity", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCity")
    @ResponseWrapper(localName = "GetCityResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCityResponse")
    public ArrayOfCityS getCity();

    /**
     * 
     * @return
     *     returns org.tempuri.ArrayOfCityAndCountry
     */
    @WebMethod(operationName = "GetCityAndCountry", action = "http://tempuri.org/GetCityAndCountry")
    @WebResult(name = "GetCityAndCountryResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCityAndCountry", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCityAndCountry")
    @ResponseWrapper(localName = "GetCityAndCountryResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCityAndCountryResponse")
    public ArrayOfCityAndCountry getCityAndCountry();

    /**
     * 
     * @param city1
     * @param city2
     * @param data
     * @return
     *     returns org.tempuri.ArrayOfPathL
     */
    @WebMethod(operationName = "FindPath", action = "http://tempuri.org/FindPath")
    @WebResult(name = "FindPathResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "FindPath", targetNamespace = "http://tempuri.org/", className = "org.tempuri.FindPath")
    @ResponseWrapper(localName = "FindPathResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.FindPathResponse")
    public ArrayOfPathL findPath(
        @WebParam(name = "city1", targetNamespace = "http://tempuri.org/")
        int city1,
        @WebParam(name = "city2", targetNamespace = "http://tempuri.org/")
        int city2,
        @WebParam(name = "data", targetNamespace = "http://tempuri.org/")
        String data);

    /**
     * 
     * @return
     *     returns org.tempuri.ArrayOfValyta
     */
    @WebMethod(operationName = "GetCurrency", action = "http://tempuri.org/GetCurrency")
    @WebResult(name = "GetCurrencyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCurrency", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCurrency")
    @ResponseWrapper(localName = "GetCurrencyResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCurrencyResponse")
    public ArrayOfValyta getCurrency();

    /**
     * 
     * @return
     *     returns org.tempuri.ArrayOfTarif
     */
    @WebMethod(operationName = "GetTarif", action = "http://tempuri.org/GetTarif")
    @WebResult(name = "GetTarifResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetTarif", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetTarif")
    @ResponseWrapper(localName = "GetTarifResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetTarifResponse")
    public ArrayOfTarif getTarif();

    /**
     * 
     * @param date
     * @param city1
     * @param city2
     * @param routeId
     * @param currency
     * @param type
     * @return
     *     returns org.tempuri.PriceCLient
     */
    @WebMethod(operationName = "GetPrice", action = "http://tempuri.org/GetPrice")
    @WebResult(name = "GetPriceResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetPrice", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPrice")
    @ResponseWrapper(localName = "GetPriceResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPriceResponse")
    public PriceCLient getPrice(
        @WebParam(name = "city1", targetNamespace = "http://tempuri.org/")
        int city1,
        @WebParam(name = "city2", targetNamespace = "http://tempuri.org/")
        int city2,
        @WebParam(name = "date", targetNamespace = "http://tempuri.org/")
        String date,
        @WebParam(name = "currency", targetNamespace = "http://tempuri.org/")
        int currency,
        @WebParam(name = "type", targetNamespace = "http://tempuri.org/")
        int type,
        @WebParam(name = "routeId", targetNamespace = "http://tempuri.org/")
        Integer routeId);

    /**
     * 
     * @param ticket
     * @param pass
     * @param login
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AnaluteTicket", action = "http://tempuri.org/AnaluteTicket")
    @WebResult(name = "AnaluteTicketResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AnaluteTicket", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AnaluteTicket")
    @ResponseWrapper(localName = "AnaluteTicketResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AnaluteTicketResponse")
    public String analuteTicket(
        @WebParam(name = "login", targetNamespace = "http://tempuri.org/")
        String login,
        @WebParam(name = "pass", targetNamespace = "http://tempuri.org/")
        String pass,
        @WebParam(name = "ticket", targetNamespace = "http://tempuri.org/")
        String ticket);

    /**
     * 
     * @param ticket
     * @param pass
     * @param login
     * @return
     *     returns org.tempuri.CancelTicket
     */
    @WebMethod(operationName = "CancelationTicket", action = "http://tempuri.org/CancelationTicket")
    @WebResult(name = "CancelationTicketResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CancelationTicket", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelationTicket")
    @ResponseWrapper(localName = "CancelationTicketResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelationTicketResponse")
    public CancelTicket cancelationTicket(
        @WebParam(name = "login", targetNamespace = "http://tempuri.org/")
        String login,
        @WebParam(name = "pass", targetNamespace = "http://tempuri.org/")
        String pass,
        @WebParam(name = "ticket", targetNamespace = "http://tempuri.org/")
        String ticket);

    /**
     * 
     * @param dateReturn
     * @param city1
     * @param city2
     * @param pass
     * @param count
     * @param dateDepart
     * @param pathId
     * @param login
     * @param pathIdReturn
     * @return
     *     returns org.tempuri.ArrayOfString
     */
    @WebMethod(operationName = "BookingTicket", action = "http://tempuri.org/BookingTicket")
    @WebResult(name = "BookingTicketResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "BookingTicket", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BookingTicket")
    @ResponseWrapper(localName = "BookingTicketResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BookingTicketResponse")
    public ArrayOfString bookingTicket(
        @WebParam(name = "login", targetNamespace = "http://tempuri.org/")
        String login,
        @WebParam(name = "pass", targetNamespace = "http://tempuri.org/")
        String pass,
        @WebParam(name = "city1", targetNamespace = "http://tempuri.org/")
        int city1,
        @WebParam(name = "city2", targetNamespace = "http://tempuri.org/")
        int city2,
        @WebParam(name = "count", targetNamespace = "http://tempuri.org/")
        int count,
        @WebParam(name = "dateDepart", targetNamespace = "http://tempuri.org/")
        String dateDepart,
        @WebParam(name = "dateReturn", targetNamespace = "http://tempuri.org/")
        String dateReturn,
        @WebParam(name = "pathId", targetNamespace = "http://tempuri.org/")
        String pathId,
        @WebParam(name = "pathIdReturn", targetNamespace = "http://tempuri.org/")
        String pathIdReturn);

    /**
     * 
     * @param ticketNumber
     * @param pass
     * @param login
     * @return
     *     returns byte[]
     */
    @WebMethod(operationName = "PrintPdf", action = "http://tempuri.org/PrintPdf")
    @WebResult(name = "PrintPdfResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "PrintPdf", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PrintPdf")
    @ResponseWrapper(localName = "PrintPdfResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PrintPdfResponse")
    public byte[] printPdf(
        @WebParam(name = "login", targetNamespace = "http://tempuri.org/")
        String login,
        @WebParam(name = "pass", targetNamespace = "http://tempuri.org/")
        String pass,
        @WebParam(name = "ticketNumber", targetNamespace = "http://tempuri.org/")
        String ticketNumber);

    /**
     * 
     * @param birthDay
     * @param city1
     * @param clientLastName
     * @param city2
     * @param pass
     * @param clientEmail
     * @param numberTicket
     * @param dateDepart
     * @param login
     * @param clientPasport
     * @param clientPhone
     * @param dateReturn
     * @param tarif
     * @param clientFirstName
     * @param currency
     * @param middleName
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "CreateTicket", action = "http://tempuri.org/CreateTicket")
    @WebResult(name = "CreateTicketResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CreateTicket", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CreateTicket")
    @ResponseWrapper(localName = "CreateTicketResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CreateTicketResponse")
    public boolean createTicket(
        @WebParam(name = "login", targetNamespace = "http://tempuri.org/")
        String login,
        @WebParam(name = "pass", targetNamespace = "http://tempuri.org/")
        String pass,
        @WebParam(name = "numberTicket", targetNamespace = "http://tempuri.org/")
        String numberTicket,
        @WebParam(name = "city1", targetNamespace = "http://tempuri.org/")
        int city1,
        @WebParam(name = "city2", targetNamespace = "http://tempuri.org/")
        int city2,
        @WebParam(name = "dateDepart", targetNamespace = "http://tempuri.org/")
        String dateDepart,
        @WebParam(name = "dateReturn", targetNamespace = "http://tempuri.org/")
        String dateReturn,
        @WebParam(name = "tarif", targetNamespace = "http://tempuri.org/")
        int tarif,
        @WebParam(name = "currency", targetNamespace = "http://tempuri.org/")
        int currency,
        @WebParam(name = "clientFirstName", targetNamespace = "http://tempuri.org/")
        String clientFirstName,
        @WebParam(name = "clientLastName", targetNamespace = "http://tempuri.org/")
        String clientLastName,
        @WebParam(name = "clientPasport", targetNamespace = "http://tempuri.org/")
        String clientPasport,
        @WebParam(name = "clientPhone", targetNamespace = "http://tempuri.org/")
        String clientPhone,
        @WebParam(name = "clientEmail", targetNamespace = "http://tempuri.org/")
        String clientEmail,
        @WebParam(name = "MiddleName", targetNamespace = "http://tempuri.org/")
        String middleName,
        @WebParam(name = "BirthDay", targetNamespace = "http://tempuri.org/")
        String birthDay);

    /**
     * 
     * @param city1
     * @param city2
     * @param dateDepart
     * @return
     *     returns org.tempuri.ArrayOfStopPath
     */
    @WebMethod(operationName = "GetStopPath", action = "http://tempuri.org/GetStopPath")
    @WebResult(name = "GetStopPathResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetStopPath", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetStopPath")
    @ResponseWrapper(localName = "GetStopPathResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetStopPathResponse")
    public ArrayOfStopPath getStopPath(
        @WebParam(name = "city1", targetNamespace = "http://tempuri.org/")
        int city1,
        @WebParam(name = "city2", targetNamespace = "http://tempuri.org/")
        int city2,
        @WebParam(name = "dateDepart", targetNamespace = "http://tempuri.org/")
        String dateDepart);

}
